### ISSUE TITLE
This script is made for the old HelloID products with only actions tab. Will not work with Actions - New Tab used.

### ISSUE THREAD

**Issue by ovanhooff** [Tools4everBV/HelloID-Conn-SA-Sync-AzureActiveDirectory-Groupmemberships-To-SelfService-Productassignments#4]
$splatParams = @{
        Method   = "GET"
        Uri      = "selfservice/actions"
        PageSize = 1000
    }
    $helloIDSelfServiceProductActions = Invoke-HIDRestMethod @splatParams

This will not work if you use the Actions - new TAB.

How can I resolve this issue?

**Comment by JeroenBL** [comment]
Hi @ovanhooff

Thank you for taking the time to create this issue!

We have API information available at: [Add or Update a Product API Documentation](https://apidocs.helloid.com/docs/helloid/ev3qn3p1nirbd-add-or-update-a-product). You may also want to look at how it's implemented in another sync task [here](https://github.com/Tools4everBV/HelloID-Conn-SA-Sync-ActiveDirectory-Groups-To-SelfService-Products/blob/main/Sync-AD-Groups-To-Products.ps1#L879).

I expect this task to be updated in the near future, but I don't have a specific timeline for that at this moment. 

Best regards,
Jeroen
